import type { APIRoute } from 'astro';
import { absoluteUrl } from '../site.config';

// AI Crawler Configuration based on GEO best practices
// Reference: https://tw93.fun/2026-05-01/ai-visibility.html
export const GET: APIRoute = () =>
  new Response(
    [
      '# David Blog - AI Crawler Configuration',
      '# GEO: Generative Engine Optimization',
      '',
      '# ============================================',
      '# Search & Retrieval Bots (allow) - These power AI search',
      '# ============================================',
      '',
      'User-agent: OAI-SearchBot',
      'Allow: /',
      '',
      'User-agent: Claude-SearchBot',
      'Allow: /',
      '',
      'User-agent: PerplexityBot',
      'Allow: /',
      '',
      '# ============================================',
      '# User-Triggered Bots (allow) - "Summarize this page" requests',
      '# ============================================',
      '',
      'User-agent: ChatGPT-User',
      'Allow: /',
      '',
      'User-agent: Claude-User',
      'Allow: /',
      '',
      '# ============================================',
      '# Training Bots (block) - Don\'t use our content to train models',
      '# ============================================',
      '',
      'User-agent: GPTBot',
      'Disallow: /',
      '',
      'User-agent: CCBot',
      'Disallow: /',
      '',
      'User-agent: ClaudeBot',
      'Disallow: /',
      '',
      'User-agent: Meta-ExternalAgent',
      'Disallow: /',
      '',
      'User-agent: Google-Extended',
      'Disallow: /',
      '',
      'User-agent: Applebot-Extended',
      'Disallow: /',
      '',
      '# ============================================',
      '# Undeclared Bots (block) - Don\'t play nice',
      '# ============================================',
      '',
      'User-agent: Bytespider',
      'Disallow: /',
      '',
      'User-agent: Googlebot',
      'Allow: /',
      '',
      'User-agent: Bingbot',
      'Allow: /',
      '',
      '# ============================================',
      '# Sitemap',
      '# ============================================',
      '',
      `Sitemap: ${absoluteUrl('/sitemap-index.xml')}`,
      `Sitemap: ${absoluteUrl('/llms.txt')}`
    ].join('\n'),
    {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8'
      }
    }
  );
