import type { APIRoute } from 'astro';
import { absoluteUrl } from '../site.config';

// AI Crawler Configuration based on GEO best practices
// Reference: https://tw93.fun/2026-05-01/ai-visibility.html
export const GET: APIRoute = () =>
  new Response(
    [
      '# David Blog - AI Crawler Configuration',
      '# GEO: Generative Engine Optimization',
      '',
      '# ============================================',
      '# Content Signals - AI content usage preferences',
      '# https://contentsignals.org/',
      '# ============================================',
      '# ai-train=no:  Do not use site content for training models',
      '# search=yes:   Allow content to appear in AI search results',
      '# ai-input=no:  Do not use content as real-time AI input',
      '# Content-Signal: ai-train=no, search=yes, ai-input=no',
      '',
      '# ============================================',
      '# Search & Retrieval Bots (allow) - These power AI search',
      '# ============================================',
      '',
      'User-agent: OAI-SearchBot',
      'Content-Signal: ai-train=no, search=yes, ai-input=no',
      'Allow: /',
      '',
      'User-agent: Claude-SearchBot',
      'Content-Signal: ai-train=no, search=yes, ai-input=no',
      'Allow: /',
      '',
      'User-agent: PerplexityBot',
      'Content-Signal: ai-train=no, search=yes, ai-input=no',
      'Allow: /',
      '',
      '# ============================================',
      '# User-Triggered Bots (allow) - "Summarize this page" requests',
      '# ============================================',
      '',
      'User-agent: ChatGPT-User',
      'Content-Signal: ai-train=no, search=yes, ai-input=yes',
      'Allow: /',
      '',
      'User-agent: Claude-User',
      'Content-Signal: ai-train=no, search=yes, ai-input=yes',
      'Allow: /',
      '',
      '# ============================================',
      '# Training Bots (block) - Don\'t use our content to train models',
      '# ============================================',
      '',
      'User-agent: GPTBot',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: CCBot',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: ClaudeBot',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: Meta-ExternalAgent',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: Google-Extended',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: Applebot-Extended',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      '# ============================================',
      '# Undeclared Bots (block) - Don\'t play nice',
      '# ============================================',
      '',
      'User-agent: Bytespider',
      'Content-Signal: ai-train=no, search=no, ai-input=no',
      'Disallow: /',
      '',
      'User-agent: Googlebot',
      'Content-Signal: ai-train=no, search=yes, ai-input=no',
      'Allow: /',
      '',
      'User-agent: Bingbot',
      'Content-Signal: ai-train=no, search=yes, ai-input=no',
      'Allow: /',
      '',
      '# ============================================',
      '# Sitemap',
      '# ============================================',
      '',
      `Sitemap: ${absoluteUrl('/sitemap-index.xml')}`,
      `Sitemap: ${absoluteUrl('/llms.txt')}`
    ].join('\n'),
    {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8'
      }
    }
  );
