name: Mirror to Codeberg

on:
  push:
    branches: ["main"]
    tags: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: mirror
  cancel-in-progress: false

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg "https://thedavidweng:${CODEBERG_TOKEN}@codeberg.org/thedavidweng/blog"
          git push codeberg main --force
          git push codeberg --tags --force
